### ISSUE TITLE
Library does not follow node idiomatic error first callback 

### ISSUE THREAD

**Issue by jtblin** [ryanbreen/node-pingdom#4]
All libraries in node return the error first in the callback, then the response. This module returns an array with the error or the response which is not friendly with other modules like `async` or `syncho` that expects an error first in the callback.

**Comment by ryanbreen** [comment]
Yep, this is poorly done.  I'll fix it soon.

**Comment by jtblin** [comment]
I can submit a PR if you want but I don't see how this fix could be backward compatible.

**Comment by ryanbreen** [comment]
It definitely won't be, but it's the right thing to do. If you want to submit a PR, I'll be happy to take a look

**Comment by ryanbreen** [comment]
I published this to NPM with a new major number to signify that it's a breaking change.

**Comment by jtblin** [comment]
Awesome. Thanks for the fast follow-up!
